// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPINPromptPort creates a new instance of MockPINPromptPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPINPromptPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPINPromptPort {
	mock := &MockPINPromptPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPINPromptPort is an autogenerated mock type for the PINPromptPort type
type MockPINPromptPort struct {
	mock.Mock
}

type MockPINPromptPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPINPromptPort) EXPECT() *MockPINPromptPort_Expecter {
	return &MockPINPromptPort_Expecter{mock: &_m.Mock}
}

// IsTTY provides a mock function for the type MockPINPromptPort
func (_mock *MockPINPromptPort) IsTTY() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTTY")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPINPromptPort_IsTTY_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTTY'
type MockPINPromptPort_IsTTY_Call struct {
	*mock.Call
}

// IsTTY is a helper method to define mock.On call
func (_e *MockPINPromptPort_Expecter) IsTTY() *MockPINPromptPort_IsTTY_Call {
	return &MockPINPromptPort_IsTTY_Call{Call: _e.mock.On("IsTTY")}
}

func (_c *MockPINPromptPort_IsTTY_Call) Run(run func()) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPINPromptPort_IsTTY_Call) Return(b bool) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPINPromptPort_IsTTY_Call) RunAndReturn(run func() bool) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Return(run)
	return _c
}

// PromptForPIN provides a mock function for the type MockPINPromptPort
func (_mock *MockPINPromptPort) PromptForPIN(ctx context.Context, errorMode bool, message string) (string, error) {
	ret := _mock.Called(ctx, errorMode, message)

	if len(ret) == 0 {
		panic("no return value specified for PromptForPIN")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string) (string, error)); ok {
		return returnFunc(ctx, errorMode, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string) string); ok {
		r0 = returnFunc(ctx, errorMode, message)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, string) error); ok {
		r1 = returnFunc(ctx, errorMode, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPINPromptPort_PromptForPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptForPIN'
type MockPINPromptPort_PromptForPIN_Call struct {
	*mock.Call
}

// PromptForPIN is a helper method to define mock.On call
//   - ctx context.Context
//   - errorMode bool
//   - message string
func (_e *MockPINPromptPort_Expecter) PromptForPIN(ctx interface{}, errorMode interface{}, message interface{}) *MockPINPromptPort_PromptForPIN_Call {
	return &MockPINPromptPort_PromptForPIN_Call{Call: _e.mock.On("PromptForPIN", ctx, errorMode, message)}
}

func (_c *MockPINPromptPort_PromptForPIN_Call) Run(run func(ctx context.Context, errorMode bool, message string)) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPINPromptPort_PromptForPIN_Call) Return(s string, err error) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPINPromptPort_PromptForPIN_Call) RunAndReturn(run func(ctx context.Context, errorMode bool, message string) (string, error)) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Return(run)
	return _c
}
