// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/sekeve/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPINPromptPort creates a new instance of MockPINPromptPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPINPromptPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPINPromptPort {
	mock := &MockPINPromptPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPINPromptPort is an autogenerated mock type for the PINPromptPort type
type MockPINPromptPort struct {
	mock.Mock
}

type MockPINPromptPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPINPromptPort) EXPECT() *MockPINPromptPort_Expecter {
	return &MockPINPromptPort_Expecter{mock: &_m.Mock}
}

// IsTTY provides a mock function for the type MockPINPromptPort
func (_mock *MockPINPromptPort) IsTTY() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTTY")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPINPromptPort_IsTTY_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTTY'
type MockPINPromptPort_IsTTY_Call struct {
	*mock.Call
}

// IsTTY is a helper method to define mock.On call
func (_e *MockPINPromptPort_Expecter) IsTTY() *MockPINPromptPort_IsTTY_Call {
	return &MockPINPromptPort_IsTTY_Call{Call: _e.mock.On("IsTTY")}
}

func (_c *MockPINPromptPort_IsTTY_Call) Run(run func()) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPINPromptPort_IsTTY_Call) Return(b bool) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPINPromptPort_IsTTY_Call) RunAndReturn(run func() bool) *MockPINPromptPort_IsTTY_Call {
	_c.Call.Return(run)
	return _c
}

// PromptForPIN provides a mock function for the type MockPINPromptPort
func (_mock *MockPINPromptPort) PromptForPIN(ctx context.Context, validate port.PINValidateFunc) error {
	ret := _mock.Called(ctx, validate)

	if len(ret) == 0 {
		panic("no return value specified for PromptForPIN")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.PINValidateFunc) error); ok {
		r0 = returnFunc(ctx, validate)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPINPromptPort_PromptForPIN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptForPIN'
type MockPINPromptPort_PromptForPIN_Call struct {
	*mock.Call
}

// PromptForPIN is a helper method to define mock.On call
//   - ctx context.Context
//   - validate port.PINValidateFunc
func (_e *MockPINPromptPort_Expecter) PromptForPIN(ctx interface{}, validate interface{}) *MockPINPromptPort_PromptForPIN_Call {
	return &MockPINPromptPort_PromptForPIN_Call{Call: _e.mock.On("PromptForPIN", ctx, validate)}
}

func (_c *MockPINPromptPort_PromptForPIN_Call) Run(run func(ctx context.Context, validate port.PINValidateFunc)) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.PINValidateFunc
		if args[1] != nil {
			arg1 = args[1].(port.PINValidateFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPINPromptPort_PromptForPIN_Call) Return(err error) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPINPromptPort_PromptForPIN_Call) RunAndReturn(run func(ctx context.Context, validate port.PINValidateFunc) error) *MockPINPromptPort_PromptForPIN_Call {
	_c.Call.Return(run)
	return _c
}
