// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/sekeve/internal/domain/entity"
	"github.com/bnema/sekeve/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncPort creates a new instance of MockSyncPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncPort {
	mock := &MockSyncPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncPort is an autogenerated mock type for the SyncPort type
type MockSyncPort struct {
	mock.Mock
}

type MockSyncPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncPort) EXPECT() *MockSyncPort_Expecter {
	return &MockSyncPort_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) Authenticate(ctx context.Context, gpgKeyID string, crypto port.CryptoPort) (string, error) {
	ret := _mock.Called(ctx, gpgKeyID, crypto)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, port.CryptoPort) (string, error)); ok {
		return returnFunc(ctx, gpgKeyID, crypto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, port.CryptoPort) string); ok {
		r0 = returnFunc(ctx, gpgKeyID, crypto)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, port.CryptoPort) error); ok {
		r1 = returnFunc(ctx, gpgKeyID, crypto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockSyncPort_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - gpgKeyID string
//   - crypto port.CryptoPort
func (_e *MockSyncPort_Expecter) Authenticate(ctx interface{}, gpgKeyID interface{}, crypto interface{}) *MockSyncPort_Authenticate_Call {
	return &MockSyncPort_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, gpgKeyID, crypto)}
}

func (_c *MockSyncPort_Authenticate_Call) Run(run func(ctx context.Context, gpgKeyID string, crypto port.CryptoPort)) *MockSyncPort_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 port.CryptoPort
		if args[2] != nil {
			arg2 = args[2].(port.CryptoPort)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSyncPort_Authenticate_Call) Return(token string, err error) *MockSyncPort_Authenticate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockSyncPort_Authenticate_Call) RunAndReturn(run func(ctx context.Context, gpgKeyID string, crypto port.CryptoPort) (string, error)) *MockSyncPort_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSyncPort_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSyncPort_Expecter) Close(ctx interface{}) *MockSyncPort_Close_Call {
	return &MockSyncPort_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSyncPort_Close_Call) Run(run func(ctx context.Context)) *MockSyncPort_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSyncPort_Close_Call) Return(err error) *MockSyncPort_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockSyncPort_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) CreateEntry(ctx context.Context, envelope *entity.Envelope) (string, error) {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntry")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) (string, error)); ok {
		return returnFunc(ctx, envelope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) string); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Envelope) error); ok {
		r1 = returnFunc(ctx, envelope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_CreateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntry'
type MockSyncPort_CreateEntry_Call struct {
	*mock.Call
}

// CreateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockSyncPort_Expecter) CreateEntry(ctx interface{}, envelope interface{}) *MockSyncPort_CreateEntry_Call {
	return &MockSyncPort_CreateEntry_Call{Call: _e.mock.On("CreateEntry", ctx, envelope)}
}

func (_c *MockSyncPort_CreateEntry_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockSyncPort_CreateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_CreateEntry_Call) Return(s string, err error) *MockSyncPort_CreateEntry_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSyncPort_CreateEntry_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) (string, error)) *MockSyncPort_CreateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) DeleteEntry(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockSyncPort_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSyncPort_Expecter) DeleteEntry(ctx interface{}, name interface{}) *MockSyncPort_DeleteEntry_Call {
	return &MockSyncPort_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, name)}
}

func (_c *MockSyncPort_DeleteEntry_Call) Run(run func(ctx context.Context, name string)) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_DeleteEntry_Call) Return(err error) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_DeleteEntry_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) GetEntry(ctx context.Context, name string) (*entity.Envelope, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Envelope, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Envelope); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type MockSyncPort_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSyncPort_Expecter) GetEntry(ctx interface{}, name interface{}) *MockSyncPort_GetEntry_Call {
	return &MockSyncPort_GetEntry_Call{Call: _e.mock.On("GetEntry", ctx, name)}
}

func (_c *MockSyncPort_GetEntry_Call) Run(run func(ctx context.Context, name string)) *MockSyncPort_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_GetEntry_Call) Return(envelope *entity.Envelope, err error) *MockSyncPort_GetEntry_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockSyncPort_GetEntry_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Envelope, error)) *MockSyncPort_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntries provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) ListEntries(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error) {
	ret := _mock.Called(ctx, entryType)

	if len(ret) == 0 {
		panic("no return value specified for ListEntries")
	}

	var r0 []*entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) ([]*entity.Envelope, error)); ok {
		return returnFunc(ctx, entryType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) []*entity.Envelope); ok {
		r0 = returnFunc(ctx, entryType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntryType) error); ok {
		r1 = returnFunc(ctx, entryType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_ListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntries'
type MockSyncPort_ListEntries_Call struct {
	*mock.Call
}

// ListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - entryType entity.EntryType
func (_e *MockSyncPort_Expecter) ListEntries(ctx interface{}, entryType interface{}) *MockSyncPort_ListEntries_Call {
	return &MockSyncPort_ListEntries_Call{Call: _e.mock.On("ListEntries", ctx, entryType)}
}

func (_c *MockSyncPort_ListEntries_Call) Run(run func(ctx context.Context, entryType entity.EntryType)) *MockSyncPort_ListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntryType
		if args[1] != nil {
			arg1 = args[1].(entity.EntryType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_ListEntries_Call) Return(envelopes []*entity.Envelope, err error) *MockSyncPort_ListEntries_Call {
	_c.Call.Return(envelopes, err)
	return _c
}

func (_c *MockSyncPort_ListEntries_Call) RunAndReturn(run func(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error)) *MockSyncPort_ListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) UpdateEntry(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type MockSyncPort_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockSyncPort_Expecter) UpdateEntry(ctx interface{}, envelope interface{}) *MockSyncPort_UpdateEntry_Call {
	return &MockSyncPort_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, envelope)}
}

func (_c *MockSyncPort_UpdateEntry_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_UpdateEntry_Call) Return(err error) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_UpdateEntry_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}
