// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigPort creates a new instance of MockConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigPort {
	mock := &MockConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigPort is an autogenerated mock type for the ConfigPort type
type MockConfigPort struct {
	mock.Mock
}

type MockConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigPort) EXPECT() *MockConfigPort_Expecter {
	return &MockConfigPort_Expecter{mock: &_m.Mock}
}

// GPGKeyID provides a mock function for the type MockConfigPort
func (_mock *MockConfigPort) GPGKeyID(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GPGKeyID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigPort_GPGKeyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GPGKeyID'
type MockConfigPort_GPGKeyID_Call struct {
	*mock.Call
}

// GPGKeyID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigPort_Expecter) GPGKeyID(ctx interface{}) *MockConfigPort_GPGKeyID_Call {
	return &MockConfigPort_GPGKeyID_Call{Call: _e.mock.On("GPGKeyID", ctx)}
}

func (_c *MockConfigPort_GPGKeyID_Call) Run(run func(ctx context.Context)) *MockConfigPort_GPGKeyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigPort_GPGKeyID_Call) Return(s string) *MockConfigPort_GPGKeyID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigPort_GPGKeyID_Call) RunAndReturn(run func(ctx context.Context) string) *MockConfigPort_GPGKeyID_Call {
	_c.Call.Return(run)
	return _c
}

// IsUnconfigured provides a mock function for the type MockConfigPort
func (m *MockConfigPort) IsUnconfigured() bool {
	args := m.Called()
	return args.Bool(0)
}

// SaveSessionToken provides a mock function for the type MockConfigPort
func (_mock *MockConfigPort) SaveSessionToken(ctx context.Context, token string, ttl int64) error {
	ret := _mock.Called(ctx, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveSessionToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigPort_SaveSessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSessionToken'
type MockConfigPort_SaveSessionToken_Call struct {
	*mock.Call
}

// SaveSessionToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - ttl int64
func (_e *MockConfigPort_Expecter) SaveSessionToken(ctx interface{}, token interface{}, ttl interface{}) *MockConfigPort_SaveSessionToken_Call {
	return &MockConfigPort_SaveSessionToken_Call{Call: _e.mock.On("SaveSessionToken", ctx, token, ttl)}
}

func (_c *MockConfigPort_SaveSessionToken_Call) Run(run func(ctx context.Context, token string, ttl int64)) *MockConfigPort_SaveSessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConfigPort_SaveSessionToken_Call) Return(err error) *MockConfigPort_SaveSessionToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigPort_SaveSessionToken_Call) RunAndReturn(run func(ctx context.Context, token string, ttl int64) error) *MockConfigPort_SaveSessionToken_Call {
	_c.Call.Return(run)
	return _c
}

// ServerAddr provides a mock function for the type MockConfigPort
func (_mock *MockConfigPort) ServerAddr(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ServerAddr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigPort_ServerAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerAddr'
type MockConfigPort_ServerAddr_Call struct {
	*mock.Call
}

// ServerAddr is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigPort_Expecter) ServerAddr(ctx interface{}) *MockConfigPort_ServerAddr_Call {
	return &MockConfigPort_ServerAddr_Call{Call: _e.mock.On("ServerAddr", ctx)}
}

func (_c *MockConfigPort_ServerAddr_Call) Run(run func(ctx context.Context)) *MockConfigPort_ServerAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigPort_ServerAddr_Call) Return(s string) *MockConfigPort_ServerAddr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigPort_ServerAddr_Call) RunAndReturn(run func(ctx context.Context) string) *MockConfigPort_ServerAddr_Call {
	_c.Call.Return(run)
	return _c
}

// SessionToken provides a mock function for the type MockConfigPort
func (_mock *MockConfigPort) SessionToken(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SessionToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigPort_SessionToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionToken'
type MockConfigPort_SessionToken_Call struct {
	*mock.Call
}

// SessionToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigPort_Expecter) SessionToken(ctx interface{}) *MockConfigPort_SessionToken_Call {
	return &MockConfigPort_SessionToken_Call{Call: _e.mock.On("SessionToken", ctx)}
}

func (_c *MockConfigPort_SessionToken_Call) Run(run func(ctx context.Context)) *MockConfigPort_SessionToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigPort_SessionToken_Call) Return(s string, err error) *MockConfigPort_SessionToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfigPort_SessionToken_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockConfigPort_SessionToken_Call {
	_c.Call.Return(run)
	return _c
}
