// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/sekeve/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStoragePort creates a new instance of MockStoragePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoragePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoragePort {
	mock := &MockStoragePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoragePort is an autogenerated mock type for the StoragePort type
type MockStoragePort struct {
	mock.Mock
}

type MockStoragePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoragePort) EXPECT() *MockStoragePort_Expecter {
	return &MockStoragePort_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStoragePort_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStoragePort_Expecter) Close(ctx interface{}) *MockStoragePort_Close_Call {
	return &MockStoragePort_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockStoragePort_Close_Call) Run(run func(ctx context.Context)) *MockStoragePort_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoragePort_Close_Call) Return(err error) *MockStoragePort_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockStoragePort_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Create(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStoragePort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockStoragePort_Expecter) Create(ctx interface{}, envelope interface{}) *MockStoragePort_Create_Call {
	return &MockStoragePort_Create_Call{Call: _e.mock.On("Create", ctx, envelope)}
}

func (_c *MockStoragePort_Create_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockStoragePort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Create_Call) Return(err error) *MockStoragePort_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Create_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockStoragePort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockStoragePort_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStoragePort_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockStoragePort_DeleteByID_Call {
	return &MockStoragePort_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockStoragePort_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockStoragePort_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_DeleteByID_Call) Return(err error) *MockStoragePort_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockStoragePort_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) GetByID(ctx context.Context, id string) (*entity.Envelope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Envelope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Envelope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoragePort_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockStoragePort_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStoragePort_Expecter) GetByID(ctx interface{}, id interface{}) *MockStoragePort_GetByID_Call {
	return &MockStoragePort_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockStoragePort_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockStoragePort_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_GetByID_Call) Return(envelope *entity.Envelope, err error) *MockStoragePort_GetByID_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockStoragePort_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Envelope, error)) *MockStoragePort_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) List(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error) {
	ret := _mock.Called(ctx, entryType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) ([]*entity.Envelope, error)); ok {
		return returnFunc(ctx, entryType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) []*entity.Envelope); ok {
		r0 = returnFunc(ctx, entryType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntryType) error); ok {
		r1 = returnFunc(ctx, entryType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoragePort_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStoragePort_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - entryType entity.EntryType
func (_e *MockStoragePort_Expecter) List(ctx interface{}, entryType interface{}) *MockStoragePort_List_Call {
	return &MockStoragePort_List_Call{Call: _e.mock.On("List", ctx, entryType)}
}

func (_c *MockStoragePort_List_Call) Run(run func(ctx context.Context, entryType entity.EntryType)) *MockStoragePort_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntryType
		if args[1] != nil {
			arg1 = args[1].(entity.EntryType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_List_Call) Return(envelopes []*entity.Envelope, err error) *MockStoragePort_List_Call {
	_c.Call.Return(envelopes, err)
	return _c
}

func (_c *MockStoragePort_List_Call) RunAndReturn(run func(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error)) *MockStoragePort_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Update(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStoragePort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockStoragePort_Expecter) Update(ctx interface{}, envelope interface{}) *MockStoragePort_Update_Call {
	return &MockStoragePort_Update_Call{Call: _e.mock.On("Update", ctx, envelope)}
}

func (_c *MockStoragePort_Update_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockStoragePort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Update_Call) Return(err error) *MockStoragePort_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Update_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockStoragePort_Update_Call {
	_c.Call.Return(run)
	return _c
}
