version: 2

builds:
  - main: ./cmd/sekeve
    binary: sekeve
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=runtimesecret
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/bnema/sekeve/internal/version.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
      - "ghcr.io/bnema/sekeve:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/bnema/sekeve:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/bnema/sekeve:{{ .Version }}"
    image_templates:
      - "ghcr.io/bnema/sekeve:{{ .Version }}-amd64"
      - "ghcr.io/bnema/sekeve:{{ .Version }}-arm64"
  - name_template: "ghcr.io/bnema/sekeve:latest"
    image_templates:
      - "ghcr.io/bnema/sekeve:{{ .Version }}-amd64"
      - "ghcr.io/bnema/sekeve:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: bnema
    name: sekeve
