all: false
dir: "internal/port/mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}"
pkgname: "mocks"
packages:
  github.com/bnema/sekeve/internal/port:
    interfaces:
      StoragePort:
      CryptoPort:
      SyncPort:
      ConfigPort:
