// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCryptoPort creates a new instance of MockCryptoPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptoPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptoPort {
	mock := &MockCryptoPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCryptoPort is an autogenerated mock type for the CryptoPort type
type MockCryptoPort struct {
	mock.Mock
}

type MockCryptoPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptoPort) EXPECT() *MockCryptoPort_Expecter {
	return &MockCryptoPort_Expecter{mock: &_m.Mock}
}

// DecryptAndUse provides a mock function for the type MockCryptoPort
func (_mock *MockCryptoPort) DecryptAndUse(ctx context.Context, ciphertext []byte, fn func(plaintext []byte)) error {
	ret := _mock.Called(ctx, ciphertext, fn)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, func(plaintext []byte)) error); ok {
		r0 = returnFunc(ctx, ciphertext, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCryptoPort_DecryptAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptAndUse'
type MockCryptoPort_DecryptAndUse_Call struct {
	*mock.Call
}

// DecryptAndUse is a helper method to define mock.On call
//   - ctx context.Context
//   - ciphertext []byte
//   - fn func(plaintext []byte)
func (_e *MockCryptoPort_Expecter) DecryptAndUse(ctx interface{}, ciphertext interface{}, fn interface{}) *MockCryptoPort_DecryptAndUse_Call {
	return &MockCryptoPort_DecryptAndUse_Call{Call: _e.mock.On("DecryptAndUse", ctx, ciphertext, fn)}
}

func (_c *MockCryptoPort_DecryptAndUse_Call) Run(run func(ctx context.Context, ciphertext []byte, fn func(plaintext []byte))) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 func(plaintext []byte)
		if args[2] != nil {
			arg2 = args[2].(func(plaintext []byte))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCryptoPort_DecryptAndUse_Call) Return(err error) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCryptoPort_DecryptAndUse_Call) RunAndReturn(run func(ctx context.Context, ciphertext []byte, fn func(plaintext []byte)) error) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCryptoPort
func (_mock *MockCryptoPort) Encrypt(ctx context.Context, plaintext []byte, keyID string) ([]byte, error) {
	ret := _mock.Called(ctx, plaintext, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) ([]byte, error)); ok {
		return returnFunc(ctx, plaintext, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) []byte); ok {
		r0 = returnFunc(ctx, plaintext, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = returnFunc(ctx, plaintext, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptoPort_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCryptoPort_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - plaintext []byte
//   - keyID string
func (_e *MockCryptoPort_Expecter) Encrypt(ctx interface{}, plaintext interface{}, keyID interface{}) *MockCryptoPort_Encrypt_Call {
	return &MockCryptoPort_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, plaintext, keyID)}
}

func (_c *MockCryptoPort_Encrypt_Call) Run(run func(ctx context.Context, plaintext []byte, keyID string)) *MockCryptoPort_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCryptoPort_Encrypt_Call) Return(bytes []byte, err error) *MockCryptoPort_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCryptoPort_Encrypt_Call) RunAndReturn(run func(ctx context.Context, plaintext []byte, keyID string) ([]byte, error)) *MockCryptoPort_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
