// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package port

import (
	"context"

	"github.com/bnema/sekeve/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCryptoPort creates a new instance of MockCryptoPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptoPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptoPort {
	mock := &MockCryptoPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCryptoPort is an autogenerated mock type for the CryptoPort type
type MockCryptoPort struct {
	mock.Mock
}

type MockCryptoPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptoPort) EXPECT() *MockCryptoPort_Expecter {
	return &MockCryptoPort_Expecter{mock: &_m.Mock}
}

// DecryptAndUse provides a mock function for the type MockCryptoPort
func (_mock *MockCryptoPort) DecryptAndUse(ctx context.Context, ciphertext []byte, fn func(plaintext []byte)) error {
	ret := _mock.Called(ctx, ciphertext, fn)

	if len(ret) == 0 {
		panic("no return value specified for DecryptAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, func(plaintext []byte)) error); ok {
		r0 = returnFunc(ctx, ciphertext, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCryptoPort_DecryptAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptAndUse'
type MockCryptoPort_DecryptAndUse_Call struct {
	*mock.Call
}

// DecryptAndUse is a helper method to define mock.On call
//   - ctx context.Context
//   - ciphertext []byte
//   - fn func(plaintext []byte)
func (_e *MockCryptoPort_Expecter) DecryptAndUse(ctx interface{}, ciphertext interface{}, fn interface{}) *MockCryptoPort_DecryptAndUse_Call {
	return &MockCryptoPort_DecryptAndUse_Call{Call: _e.mock.On("DecryptAndUse", ctx, ciphertext, fn)}
}

func (_c *MockCryptoPort_DecryptAndUse_Call) Run(run func(ctx context.Context, ciphertext []byte, fn func(plaintext []byte))) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 func(plaintext []byte)
		if args[2] != nil {
			arg2 = args[2].(func(plaintext []byte))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCryptoPort_DecryptAndUse_Call) Return(err error) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCryptoPort_DecryptAndUse_Call) RunAndReturn(run func(ctx context.Context, ciphertext []byte, fn func(plaintext []byte)) error) *MockCryptoPort_DecryptAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCryptoPort
func (_mock *MockCryptoPort) Encrypt(ctx context.Context, plaintext []byte, keyID string) ([]byte, error) {
	ret := _mock.Called(ctx, plaintext, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) ([]byte, error)); ok {
		return returnFunc(ctx, plaintext, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, string) []byte); ok {
		r0 = returnFunc(ctx, plaintext, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, string) error); ok {
		r1 = returnFunc(ctx, plaintext, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCryptoPort_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCryptoPort_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - plaintext []byte
//   - keyID string
func (_e *MockCryptoPort_Expecter) Encrypt(ctx interface{}, plaintext interface{}, keyID interface{}) *MockCryptoPort_Encrypt_Call {
	return &MockCryptoPort_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, plaintext, keyID)}
}

func (_c *MockCryptoPort_Encrypt_Call) Run(run func(ctx context.Context, plaintext []byte, keyID string)) *MockCryptoPort_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCryptoPort_Encrypt_Call) Return(bytes []byte, err error) *MockCryptoPort_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCryptoPort_Encrypt_Call) RunAndReturn(run func(ctx context.Context, plaintext []byte, keyID string) ([]byte, error)) *MockCryptoPort_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStoragePort creates a new instance of MockStoragePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoragePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoragePort {
	mock := &MockStoragePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoragePort is an autogenerated mock type for the StoragePort type
type MockStoragePort struct {
	mock.Mock
}

type MockStoragePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoragePort) EXPECT() *MockStoragePort_Expecter {
	return &MockStoragePort_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStoragePort_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStoragePort_Expecter) Close(ctx interface{}) *MockStoragePort_Close_Call {
	return &MockStoragePort_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockStoragePort_Close_Call) Run(run func(ctx context.Context)) *MockStoragePort_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoragePort_Close_Call) Return(err error) *MockStoragePort_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockStoragePort_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Create(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStoragePort_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockStoragePort_Expecter) Create(ctx interface{}, envelope interface{}) *MockStoragePort_Create_Call {
	return &MockStoragePort_Create_Call{Call: _e.mock.On("Create", ctx, envelope)}
}

func (_c *MockStoragePort_Create_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockStoragePort_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Create_Call) Return(err error) *MockStoragePort_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Create_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockStoragePort_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStoragePort_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStoragePort_Expecter) Delete(ctx interface{}, name interface{}) *MockStoragePort_Delete_Call {
	return &MockStoragePort_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockStoragePort_Delete_Call) Run(run func(ctx context.Context, name string)) *MockStoragePort_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Delete_Call) Return(err error) *MockStoragePort_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockStoragePort_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Get(ctx context.Context, name string) (*entity.Envelope, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Envelope, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Envelope); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoragePort_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStoragePort_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStoragePort_Expecter) Get(ctx interface{}, name interface{}) *MockStoragePort_Get_Call {
	return &MockStoragePort_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockStoragePort_Get_Call) Run(run func(ctx context.Context, name string)) *MockStoragePort_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Get_Call) Return(envelope *entity.Envelope, err error) *MockStoragePort_Get_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockStoragePort_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Envelope, error)) *MockStoragePort_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) List(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error) {
	ret := _mock.Called(ctx, entryType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) ([]*entity.Envelope, error)); ok {
		return returnFunc(ctx, entryType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) []*entity.Envelope); ok {
		r0 = returnFunc(ctx, entryType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntryType) error); ok {
		r1 = returnFunc(ctx, entryType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoragePort_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStoragePort_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - entryType entity.EntryType
func (_e *MockStoragePort_Expecter) List(ctx interface{}, entryType interface{}) *MockStoragePort_List_Call {
	return &MockStoragePort_List_Call{Call: _e.mock.On("List", ctx, entryType)}
}

func (_c *MockStoragePort_List_Call) Run(run func(ctx context.Context, entryType entity.EntryType)) *MockStoragePort_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntryType
		if args[1] != nil {
			arg1 = args[1].(entity.EntryType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_List_Call) Return(envelopes []*entity.Envelope, err error) *MockStoragePort_List_Call {
	_c.Call.Return(envelopes, err)
	return _c
}

func (_c *MockStoragePort_List_Call) RunAndReturn(run func(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error)) *MockStoragePort_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStoragePort
func (_mock *MockStoragePort) Update(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoragePort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStoragePort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockStoragePort_Expecter) Update(ctx interface{}, envelope interface{}) *MockStoragePort_Update_Call {
	return &MockStoragePort_Update_Call{Call: _e.mock.On("Update", ctx, envelope)}
}

func (_c *MockStoragePort_Update_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockStoragePort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoragePort_Update_Call) Return(err error) *MockStoragePort_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoragePort_Update_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockStoragePort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncPort creates a new instance of MockSyncPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncPort {
	mock := &MockSyncPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncPort is an autogenerated mock type for the SyncPort type
type MockSyncPort struct {
	mock.Mock
}

type MockSyncPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncPort) EXPECT() *MockSyncPort_Expecter {
	return &MockSyncPort_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) Authenticate(ctx context.Context, gpgKeyID string, crypto CryptoPort) (string, error) {
	ret := _mock.Called(ctx, gpgKeyID, crypto)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, CryptoPort) (string, error)); ok {
		return returnFunc(ctx, gpgKeyID, crypto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, CryptoPort) string); ok {
		r0 = returnFunc(ctx, gpgKeyID, crypto)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, CryptoPort) error); ok {
		r1 = returnFunc(ctx, gpgKeyID, crypto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockSyncPort_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - gpgKeyID string
//   - crypto CryptoPort
func (_e *MockSyncPort_Expecter) Authenticate(ctx interface{}, gpgKeyID interface{}, crypto interface{}) *MockSyncPort_Authenticate_Call {
	return &MockSyncPort_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, gpgKeyID, crypto)}
}

func (_c *MockSyncPort_Authenticate_Call) Run(run func(ctx context.Context, gpgKeyID string, crypto CryptoPort)) *MockSyncPort_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 CryptoPort
		if args[2] != nil {
			arg2 = args[2].(CryptoPort)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSyncPort_Authenticate_Call) Return(token string, err error) *MockSyncPort_Authenticate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockSyncPort_Authenticate_Call) RunAndReturn(run func(ctx context.Context, gpgKeyID string, crypto CryptoPort) (string, error)) *MockSyncPort_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSyncPort_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSyncPort_Expecter) Close(ctx interface{}) *MockSyncPort_Close_Call {
	return &MockSyncPort_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSyncPort_Close_Call) Run(run func(ctx context.Context)) *MockSyncPort_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSyncPort_Close_Call) Return(err error) *MockSyncPort_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockSyncPort_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) CreateEntry(ctx context.Context, envelope *entity.Envelope) (string, error) {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntry")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) (string, error)); ok {
		return returnFunc(ctx, envelope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) string); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Envelope) error); ok {
		r1 = returnFunc(ctx, envelope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_CreateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntry'
type MockSyncPort_CreateEntry_Call struct {
	*mock.Call
}

// CreateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockSyncPort_Expecter) CreateEntry(ctx interface{}, envelope interface{}) *MockSyncPort_CreateEntry_Call {
	return &MockSyncPort_CreateEntry_Call{Call: _e.mock.On("CreateEntry", ctx, envelope)}
}

func (_c *MockSyncPort_CreateEntry_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockSyncPort_CreateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_CreateEntry_Call) Return(s string, err error) *MockSyncPort_CreateEntry_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSyncPort_CreateEntry_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) (string, error)) *MockSyncPort_CreateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) DeleteEntry(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockSyncPort_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSyncPort_Expecter) DeleteEntry(ctx interface{}, name interface{}) *MockSyncPort_DeleteEntry_Call {
	return &MockSyncPort_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, name)}
}

func (_c *MockSyncPort_DeleteEntry_Call) Run(run func(ctx context.Context, name string)) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_DeleteEntry_Call) Return(err error) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_DeleteEntry_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockSyncPort_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) GetEntry(ctx context.Context, name string) (*entity.Envelope, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Envelope, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Envelope); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type MockSyncPort_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSyncPort_Expecter) GetEntry(ctx interface{}, name interface{}) *MockSyncPort_GetEntry_Call {
	return &MockSyncPort_GetEntry_Call{Call: _e.mock.On("GetEntry", ctx, name)}
}

func (_c *MockSyncPort_GetEntry_Call) Run(run func(ctx context.Context, name string)) *MockSyncPort_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_GetEntry_Call) Return(envelope *entity.Envelope, err error) *MockSyncPort_GetEntry_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockSyncPort_GetEntry_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Envelope, error)) *MockSyncPort_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntries provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) ListEntries(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error) {
	ret := _mock.Called(ctx, entryType)

	if len(ret) == 0 {
		panic("no return value specified for ListEntries")
	}

	var r0 []*entity.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) ([]*entity.Envelope, error)); ok {
		return returnFunc(ctx, entryType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.EntryType) []*entity.Envelope); ok {
		r0 = returnFunc(ctx, entryType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.EntryType) error); ok {
		r1 = returnFunc(ctx, entryType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncPort_ListEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntries'
type MockSyncPort_ListEntries_Call struct {
	*mock.Call
}

// ListEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - entryType entity.EntryType
func (_e *MockSyncPort_Expecter) ListEntries(ctx interface{}, entryType interface{}) *MockSyncPort_ListEntries_Call {
	return &MockSyncPort_ListEntries_Call{Call: _e.mock.On("ListEntries", ctx, entryType)}
}

func (_c *MockSyncPort_ListEntries_Call) Run(run func(ctx context.Context, entryType entity.EntryType)) *MockSyncPort_ListEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.EntryType
		if args[1] != nil {
			arg1 = args[1].(entity.EntryType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_ListEntries_Call) Return(envelopes []*entity.Envelope, err error) *MockSyncPort_ListEntries_Call {
	_c.Call.Return(envelopes, err)
	return _c
}

func (_c *MockSyncPort_ListEntries_Call) RunAndReturn(run func(ctx context.Context, entryType entity.EntryType) ([]*entity.Envelope, error)) *MockSyncPort_ListEntries_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function for the type MockSyncPort
func (_mock *MockSyncPort) UpdateEntry(ctx context.Context, envelope *entity.Envelope) error {
	ret := _mock.Called(ctx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Envelope) error); ok {
		r0 = returnFunc(ctx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncPort_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type MockSyncPort_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - envelope *entity.Envelope
func (_e *MockSyncPort_Expecter) UpdateEntry(ctx interface{}, envelope interface{}) *MockSyncPort_UpdateEntry_Call {
	return &MockSyncPort_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, envelope)}
}

func (_c *MockSyncPort_UpdateEntry_Call) Run(run func(ctx context.Context, envelope *entity.Envelope)) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Envelope
		if args[1] != nil {
			arg1 = args[1].(*entity.Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncPort_UpdateEntry_Call) Return(err error) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncPort_UpdateEntry_Call) RunAndReturn(run func(ctx context.Context, envelope *entity.Envelope) error) *MockSyncPort_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}
